// Code generated by gorpc; DO NOT EDIT.

'use strict';

 
class GreeterService {
	
	async greet(greetRequest) {
		const headers = {
			'Accept':		'application/json',
			'Accept-Encoding':	'gzip',
			'Content-Type':		'application/json',
		}
		greetRequest = greetRequest || {}
		const response = await fetch('/gorpc/GreeterService.Greet', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(greetRequest)
		})
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error)
			}
			return json
		})
	}
	
}

